[lib]
crate-type = ["staticlib"]
name = "rust"

[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0.82"

[dependencies.cxx-async]
path = "../cxx-async/cxx-async"

[build-dependencies]
cxx-build = "1.0.82"
